### PR TITLE
Add jp-JP translation.

### PR DESCRIPTION
**Pull request by xubingyang**

### CODE REVIEW

**Comment by rmasoni** [comment]
@xubingyang Thank you once again! I should be able to review the actual wording and vocabulary tomorrow and get this PR approved.

**Comment by xubingyang** [comment]
@rmasoni OK. You might find some "、" in the sentences. These are not typos, Japanese goes this way.

**Comment by rmasoni** [comment]
@xubingyang 大丈夫です！僕も、日本語が少し話せます😄🇯🇵

**Comment by xubingyang** [comment]
@rmasoni 良かったですね。早くなりますね。

**Comment by rmasoni** [comment]
@xubingyang Hey, sorry for taking so long to review this. I had the translation thoroughly reviewed by a native Japanese friend, and I'll be merging this version now. Thank you so much!

**Pull request merged**
