### PR TITLE
Update Ruby and gems

### PR DESCRIPTION
**Pull request by dlibanori**
Ruby 2.2.2 is getting close to end-of-life. This PR updates to ruby 2.4.2. Unfortunately it has to update tons of gems cause they don't work well with ruby 2.4.2. It also:

- updates Rails to 2.4.10
- fixes cucumber tests that were broken
- installs Travis as CI.

[OFFTOPIC]: I am using [git-flow](https://danielkummer.github.io/git-flow-cheatsheet/index.pt_BR.html) branches

### CODE REVIEW

**Comment by rmasoni** [comment]
I don't understand the point of the `develop` branch.

Right now, approved PRs go directly to `master`, that automatically deploys to production. How does having another layer between them improve the process?

**Comment by rmasoni** [comment]
Also, is there something we can do to fix the test that failed?

**Comment by dlibanori** [comment]
@rmasoni dont worry, this happens when you are going to install travis

**Comment by dlibanori** [comment]
@rmasoni nowadays git flow is kind of a pattern to branch/tag/merge strategy/release/etc

**Comment by rmasoni** [comment]
I'll read more about it — I still can't see the advantages of doing things this way.

But anyways, we're gonna need yet another PR to merge `develop` into `master`, right?

**Comment by rmasoni** [comment]
Oh, there will be a `release` branch that's going to be merged into `master` and also back to `develop` again…

This feels like tremendous overkill. Look:

`branch` → PR → `master` (deploy)

`branch` → PR → `develop` → PR → `release` → PR → `master` (deploy) + `develop`

Am I missing something?

**Comment by dlibanori** [comment]
It is simpler, it is just:

`branch` → PR → `develop` → PR → `master` → mark tag with version number

I really don't see any utility to both, `develop` and release branch, right now. For me, just `develop`branch is fine.

**Comment by rmasoni** [comment]
I think it's better to manage the merging of named, scoped branches into `master` rather than a generic compilation.

**Comment by jonduarte** [comment]
Agree with @rmasoni there's no need for multiple branches. If the feature is good to go: merge on master. If it requires other components then we should break it on small deliverables that can be merged individually onto master.

**Comment by rmasoni** [comment]
I'll replicate this PR the conventional way.

**Pull request merged**
